package envfile

import (
	"errors"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestRender_SortedAndQuoted(t *testing.T) {
	out, err := Render(map[string]string{
		"FOO":                "bar",
		"ANTHROPIC_BASE_URL": "https://gw.acme.com/",
	})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	got := string(out)
	wantOrder := []string{"ANTHROPIC_BASE_URL", "FOO"}
	idxA := strings.Index(got, wantOrder[0])
	idxB := strings.Index(got, wantOrder[1])
	if idxA < 0 || idxB < 0 || idxA > idxB {
		t.Fatalf("expected %v in order, got:\n%s", wantOrder, got)
	}
	if !strings.Contains(got, `export FOO='bar'`) {
		t.Fatalf("missing FOO export, got:\n%s", got)
	}
}

func TestRender_QuoteEscapesSingleQuote(t *testing.T) {
	out, err := Render(map[string]string{"X": "a'b"})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if !strings.Contains(string(out), `export X='a'\''b'`) {
		t.Fatalf("escaping wrong, got:\n%s", out)
	}
}

func TestRender_RejectsNewline(t *testing.T) {
	_, err := Render(map[string]string{"X": "a\nb"})
	if !errors.Is(err, ErrUnsafeValue) {
		t.Fatalf("expected ErrUnsafeValue, got %v", err)
	}
}

func TestRender_RejectsNul(t *testing.T) {
	_, err := Render(map[string]string{"X": "a\x00b"})
	if !errors.Is(err, ErrUnsafeValue) {
		t.Fatalf("expected ErrUnsafeValue, got %v", err)
	}
}

func TestRender_RejectsBadKey(t *testing.T) {
	for _, k := range []string{"foo", "1FOO", "FOO BAR", "FOO=BAR", "", "FOO-BAR"} {
		_, err := Render(map[string]string{k: "v"})
		if !errors.Is(err, ErrInvalidKey) {
			t.Fatalf("Render with key %q: expected ErrInvalidKey, got %v", k, err)
		}
	}
}

func TestRender_EmptyMapStillProducesHeader(t *testing.T) {
	out, err := Render(nil)
	if err != nil {
		t.Fatalf("Render nil: %v", err)
	}
	if !strings.Contains(string(out), "Generated by ccswitch") {
		t.Fatalf("missing header for empty env, got:\n%s", out)
	}
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		if !strings.HasPrefix(line, "#") {
			t.Fatalf("empty env should produce only comment lines, got: %q", line)
		}
	}
}

func TestWriteActiveEnv_AtomicAndSourceable(t *testing.T) {
	dir := t.TempDir()
	if err := WriteActiveEnv(dir, map[string]string{"FOO": "bar"}); err != nil {
		t.Fatalf("Write: %v", err)
	}
	data, err := os.ReadFile(filepath.Join(dir, "active.env"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	if !strings.Contains(string(data), "export FOO='bar'") {
		t.Fatalf("missing export, got:\n%s", data)
	}
	info, _ := os.Stat(filepath.Join(dir, "active.env"))
	// Windows doesn't honor POSIX mode bits — Go reports 0o666 regardless
	// of what we passed to OpenFile. ACL-based perms are out of scope here.
	if runtime.GOOS != "windows" && info.Mode().Perm() != 0o600 {
		t.Fatalf("expected mode 0600, got %v", info.Mode().Perm())
	}
}

func TestWriteActiveEnv_OverwritesPrev(t *testing.T) {
	dir := t.TempDir()
	if err := WriteActiveEnv(dir, map[string]string{"OLD": "1"}); err != nil {
		t.Fatal(err)
	}
	if err := WriteActiveEnv(dir, map[string]string{"NEW": "2"}); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(filepath.Join(dir, "active.env"))
	if strings.Contains(string(data), "OLD") {
		t.Fatalf("old key not removed: %s", data)
	}
	if !strings.Contains(string(data), "NEW") {
		t.Fatalf("new key missing: %s", data)
	}
}
