// Package envfile writes the per-profile shell-sourceable env overlay file.
//
// Output is a sequence of POSIX export-friendly assignments:
//
//	export KEY='value'
//
// Single-quoted values, with internal `'` escaped as `'\''`. Values
// containing newlines or NULs are rejected — those would either break the
// sourcing shell or invite injection.
package envfile

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// ErrUnsafeValue is returned when an env value cannot be safely encoded
// into a sourceable shell file.
var ErrUnsafeValue = errors.New("envfile: env value contains newline or NUL byte")

// ErrInvalidKey is returned when an env key would not be POSIX-safe in a
// `export KEY=...` line. profile.ValidateEnvKey already rejects these
// upstream, but Render re-checks defensively in case a future caller
// bypasses that path.
var ErrInvalidKey = errors.New("envfile: env key must match ^[A-Z_][A-Z0-9_]*$")

var envKeyRe = regexp.MustCompile(`^[A-Z_][A-Z0-9_]*$`)

// WriteActiveEnv replaces $configDir/active.env with the rendering of env.
// An empty map writes an empty file (idempotent for shell sourcing).
func WriteActiveEnv(configDir string, env map[string]string) error {
	rendered, err := Render(env)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(configDir, 0o700); err != nil {
		return err
	}
	path := filepath.Join(configDir, "active.env")
	return writeAtomic(path, rendered, 0o600)
}

// Render returns the bytes that would be written by WriteActiveEnv.
func Render(env map[string]string) ([]byte, error) {
	keys := make([]string, 0, len(env))
	for k := range env {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var buf strings.Builder
	buf.WriteString("# Generated by ccswitch — sourced by your shell rc.\n")
	buf.WriteString("# Edit a profile's env via `ccswitch env <profile> --set KEY=VAL`.\n")
	for _, k := range keys {
		if !envKeyRe.MatchString(k) {
			return nil, fmt.Errorf("%w: %q", ErrInvalidKey, k)
		}
		v := env[k]
		if strings.ContainsAny(v, "\n\x00") {
			return nil, fmt.Errorf("%w: key %q", ErrUnsafeValue, k)
		}
		fmt.Fprintf(&buf, "export %s=%s\n", k, posixQuote(v))
	}
	return []byte(buf.String()), nil
}

// posixQuote single-quotes a string for /bin/sh, escaping internal `'`.
func posixQuote(s string) string {
	if s == "" {
		return "''"
	}
	return "'" + strings.ReplaceAll(s, "'", "'\\''") + "'"
}

func writeAtomic(path string, data []byte, mode os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".active-*.env.tmp")
	if err != nil {
		return err
	}
	cleanup := func() { _ = os.Remove(tmp.Name()) }
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		cleanup()
		return err
	}
	if err := tmp.Chmod(mode); err != nil {
		_ = tmp.Close()
		cleanup()
		return err
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		cleanup()
		return err
	}
	if err := tmp.Close(); err != nil {
		cleanup()
		return err
	}
	return os.Rename(tmp.Name(), path)
}
